services:

  server:
    build: 
      context: ./server
      dockerfile: ./Dockerfile
    restart: unless-stopped
    volumes:
      - ./server:/app
    ports:
      - 3001:3001
    env_file:
      - .env
      
  client:
    build: 
      context: ./client
      dockerfile: ./Dockerfile.client
    restart: unless-stopped
    volumes:
      - ./client:/app
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - server
    
  test-front:
    build: 
      context: ./client
      dockerfile: ./Dockerfile.testfront
    restart: unless-stopped
    volumes:
     - ./client:/app
    ports:
     - 3000:3000
    env_file:
     - .env
    depends_on:
     - server